FROM prefix-random:0.1
#FROM prefix-random:0.2
#FROM airdock/oracle-jdk

MAINTAINER My xxx<xxx@163.com>

RUN test -d "/app/bin" -a  -d "/app/lib" -a -d "/app/conf" -a -d "/app/resources" -a -d "/app/log" -a -f "/app/bin/start.sh"  &&  mkdir -p /app/control/bin

COPY ./myStart.sh /app/control/bin/